### ISSUE TITLE
Show system birthday

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/fetch#37] opened 2016-01-29 15:10 UTC
On Linux it's easy: you can read the day when `/lost+found` was created.

**Comment by dylanaraps** [comment] 2016-01-29 15:17
Sounds like something fun to add, I'll add it to my TODO list.

**Comment by dylanaraps** [comment] 2016-01-29 23:56
What does this command output? `ls -alct /|tail -1|awk '{print $6, $7, $8}'`

**Comment by mclado** [comment] 2016-01-30 08:35
System birthday like time when it was installed? I am getting "Oct 11 00:01" but thats not even close to my OS X birthday. :smile:

**Comment by dylanaraps** [comment] 2016-01-30 08:48
Yup! 

I can't seem to get the correct value without root privileges.

**Comment by mclado** [comment] 2016-01-30 10:04
After some digging in system logs here in OS X (should I stop saying OS X, because I think that you already found out that its my system :smile: ), I found that Oct 11 is pretty accurate actually. Found out I made clean install off OS X on Oct 10! But year is still missing in your command (and you can't just grep it from `ll`, or?).

**Comment by dylanaraps** [comment] 2016-01-30 10:22
What does this command output? This is the same as above but it'll print more info.

```sh
ls -alct / | tail -1
```

**Comment by mclado** [comment] 2016-01-30 10:23
` d-wx-wx-wt     2 root  wheel     68 Oct 11 00:01 .Trashes`

**Comment by dylanaraps** [comment] 2016-01-30 10:29
Ah, we still don't get the year.

**Comment by dylanaraps** [comment] 2016-01-30 10:29
I can't seem to find any other way of getting the birthday without requiring root.

**Comment by mclado** [comment] 2016-01-30 10:43
Actually, you can. Your `ls -alct / | tail -1` is missing `-T`, which, refering to manual does: 

> When used with the -l (lowercase letter ``ell'') option, display complete
             time information for the file, including month, day, hour, minute, second,
             and year.

So yeah, running `ls -alctT / | tail -1` returns `d-wx-wx-wt     2 root  wheel     68 Oct 11 00:01:17 2015 .Trashes` which is awesome! Just awk that.

**Comment by dylanaraps** [comment] 2016-01-30 10:46
Oh neat!

Ok, it turns out that the flag is different on linux. It's `--full-time` here and it prints a similar output. I'll start work on adding this now! :)

**Comment by tudurom** [comment] 2016-01-30 10:47
Another option would be getting the birthday in an OS-specific manner. For example, on Arch you can get the OS birthday by reading the first line in `/var/log/pacman.log`. This command prints the date and time when the OS got installed.

```bash
head -n 1 /var/log/pacman.log | tr -d '[]' | awk '{print $1, $2}'
```

Prints: `2015-11-27 16:40`.

A similar command can be used on Ubuntu based OS's.

**Comment by dylanaraps** [comment] 2016-01-30 10:49
The simpler we can get the function to be the better, does `ls -alct --full-time / | tail -1` include the birthdate for you @tudurom?

**Comment by tudurom** [comment] 2016-01-30 10:52
Yeah, it works. A better variant is this:

```bash
ls -alct --full-time / | tail -1 | awk '{print $6}'
```

**Comment by mclado** [comment] 2016-01-30 10:53
Oh ok, if command here is different and you have to "if" them for different distros, please use this one for OS X then: `ls -alctT /var/log/CDIS.custom`.
Prints out: `-rw-r--r--@ 1 root  wheel  12 Oct 11 07:18:56 2015 /var/log/CDIS.custom`.
It is more accurate because it represents first time the installer was started: `Oct 11 07:18:56 2015`.

**Comment by dylanaraps** [comment] 2016-01-30 10:54
@tudurom: Awesome!

@mclado: Will this work for every OS X system?

**Comment by mclado** [comment] 2016-01-30 10:56
Yes, CDIS.custom is always here. Even in cases where installer fails and even in older OS X versions.

**Comment by dylanaraps** [comment] 2016-01-30 10:56
Awesome!

**Comment by dylanaraps** [comment] 2016-01-30 10:57
I'll also add a config option to convert the output to a prettier format. So `2015-11-27` will be converted to `27th November 2015` and etc.

**Comment by tudurom** [comment] 2016-01-30 10:58
Didn't specified; the above command yields `2015-11-27`.

An even better one would be 

```bash
ls -alct --full-time / | tail -1 | tr ':' ' ' | awk '{print $6, $7 ":" $8}'
```

That shows `2015-11-27 00:39`.

**Comment by dylanaraps** [comment] 2016-01-30 11:04
The `ls -alct --full-time /` gives me a **totally** different output when run from inside the script. I'm confused as to why.

```sh
Birthday: 1970-01-01 10:00
```

**Comment by tudurom** [comment] 2016-01-30 11:05
Try this:

```bash
ls -alct --full-time / | grep "lost+found"
```

**Comment by dylanaraps** [comment] 2016-01-30 11:07
This works, awesome!

**Comment by dylanaraps** [comment] 2016-01-30 11:12
I pushed a version for you guys to test to master. The birthday line is disabled by default and can be enabled with `info "Birthday" birthday`.

What does the output look like?

**Comment by mclado** [comment] 2016-01-30 11:15
Fine with me.
Whats wrong with font? 
[img]http://i.imgur.com/6zKELe4.png[/img]

**Comment by dylanaraps** [comment] 2016-01-30 11:17
The font is the GTK theme font.

**Comment by tudurom** [comment] 2016-01-30 11:20
Looks good. Another enhancement would be specifying if you want to show the time.

![pic](https://ipfs.pics/ipfs/QmRYkvci7zznXLTc7n9aowb5cv9wd1xQVhQ1jFVTaZfd7Y)

**Comment by dylanaraps** [comment] 2016-01-30 11:22
I'm working on converting the output to a prettier format, here's what mine looks like now:

![img](http://i.imgur.com/JcZeHx9.png)

What do you guys think?

**Comment by dylanaraps** [comment] 2016-01-30 11:23
> Another enhancement would be specifying if you want to show the time.

I'll add this too!

**Comment by tudurom** [comment] 2016-01-30 11:23
Looks good! Gotta steal the terminal font.

**Comment by dylanaraps** [comment] 2016-01-30 11:24
It's called `lemon` and you can find it here: https://github.com/phallus/fonts

**Comment by tudurom** [comment] 2016-01-30 11:25
What the hell that's too small.

**Comment by dylanaraps** [comment] 2016-01-30 11:28
It takes a while to get used to it. :)

**Comment by tudurom** [comment] 2016-01-30 11:30
I will end this off-topic discussion by saying my font's called erusfont. Sorry for spamming, watchers and issue contributors.

**Comment by tudurom** [comment] 2016-01-30 11:32
May I close this issue?

**Comment by dylanaraps** [comment] 2016-01-30 11:33
I'm about to push the finished function, lets leave this open until you guys test it out.

**Comment by dylanaraps** [comment] 2016-01-30 11:46
I just pushed it to master.

There are two new flags/options:

- `--birthday_shorthand` and `$birthday_shorthand` to shorten/lengthen
    the output of birthday.
- `--birthday_time` and `$birthday_time` to show/hide the time in the output.

If it works, we can close the issue!

**Comment by tudurom** [comment] 2016-01-30 11:49
In my case it works. Does it work on Windows?

**Comment by dylanaraps** [comment] 2016-01-30 11:50
I'm testing BSD at the moment and it **doesn't** work. I'll check Windows now.

**Comment by mclado** [comment] 2016-01-30 11:51
OS X: not working, its blank except if I use --birthday_shorthand flag.

**Comment by dylanaraps** [comment] 2016-01-30 11:53
Can I see the shorthand output?

**Comment by mclado** [comment] 2016-01-30 11:53
`Birthday: Oct 11 2015 07:18`

**Comment by dylanaraps** [comment] 2016-01-30 11:55
What's the output of `date -d"Oct 11 2015 07:18" "+%a %d %b %Y %l:%M %p"`?

**Comment by mclado** [comment] 2016-01-30 11:57
Ugh, something is different. Again. 

`usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
 [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]`

**Comment by dylanaraps** [comment] 2016-01-30 11:57
This is the error I was looking for! :)

**Comment by dylanaraps** [comment] 2016-01-30 11:58
Look in `man date` and tell me what the description of the `-d` flag is. 

This is what it is on linux:

```sh
-d, --date=STRING
          display time described by STRING, not 'now'
```

**Comment by mclado** [comment] 2016-01-30 12:00
Check this out. https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/date.1.html
Also some examples below.

**Comment by dylanaraps** [comment] 2016-01-30 12:02
Thanks

**Comment by dylanaraps** [comment] 2016-01-30 12:04
What about this command?

`date -j -f"Oct 11 2015 07:18" "+%a %d %b %Y %l:%M %p"`

**Comment by mclado** [comment] 2016-01-30 12:05
Nope :/

**Comment by dylanaraps** [comment] 2016-01-30 12:06
What about this?

`date -j -f "%a %d %b %Y %l:%M %p" "Oct 11 2015 07:18"  "+%s"`

**Comment by mclado** [comment] 2016-01-30 12:12
It says illegal time format. This `"+%s"` actually just converts date to seconds or smth, because running ``date -j -f "%a %b %d %T %Z %Y" "`date`"`` does `Sat Jan 30 13:10:18 CET 2016` and appending `"+%s"` converts to `1454155814`.

**Comment by dylanaraps** [comment] 2016-01-30 12:13
Awesome, we just need to use the right time format now!

**Comment by dylanaraps** [comment] 2016-01-30 12:14
Also BSD and OS X share the same date flags, so I'm booting up a virtual machine to test.

**Comment by dylanaraps** [comment] 2016-01-30 12:29
I've figured it out! :)

I'll push it to master in a sec.

**Comment by mclado** [comment] 2016-01-30 12:38
Works like charm now. Except --birthday_time flag does nothing.

**Comment by dylanaraps** [comment] 2016-01-30 12:38
Weird, I'll see if I can reproduce this.

**Comment by mclado** [comment] 2016-01-30 12:38
Oh sorry, my bad. Works in all combinations! You can close this now.

**Comment by dylanaraps** [comment] 2016-01-30 12:40
Awesome! 

The function still doesn't work with BSD and Windows but I can work on this locally.

**Closed by dylanaraps** 2016-01-30 12:40 UTC
Labels: enhancement
