### ISSUE TITLE
OSX with ZSH: parse error

### ISSUE THREAD

**Issue by vendion** [dylanaraps/fetch#19] opened 2016-01-18 16:38 UTC
Using ZSH 5.2 on OSX 10.11.2, I get the following error when running `./fetchi:1184: parse error near '&'`.  Looking at line [line 1184](https://github.com/dylanaraps/fetch/blob/master/fetch#L1184) it seems the shell doesn't like the amperstand after the double semicolens to end the case statement.

**Comment by dylanaraps** [comment] 2016-01-18 21:11
I can reproduce this, I'll modify the script to remove the amperstand.

**Comment by dylanaraps** [comment] 2016-01-18 23:14
I've removed the `;;&` from the script but it turns out that there are more issues I'll have to fix. You'll have to use bash I'm afraid. I'm not going to add support for zsh.

Here are the issues:

1. Zsh doesn't like single bracket if statements with `==`. For example:

    This works: `[[ == ]]`

    This doesn't work: `[ == ]`

    Adding `unsetopt EQUALS` to the script fixes the issue but this command doesn't exist in other shells and causes a command not found error.

    The only other solution is to replace all single brackets with double brackets and I'm not for that.

2. `typeset`/`declare` on zsh don't support the `-n` flag

    This means that no info gets printed as I'm using typeset to update a variable on the fly. I haven't found a fix for this.

**Closed by dylanaraps** 2016-01-18 23:14 UTC
