### ISSUE TITLE
Add asciiart support

### ISSUE THREAD

**Issue by aloisdg** [dylanaraps/fetch#28] opened 2016-01-27 09:45 UTC
Hello,

I made a small script to print ascii art with term color. You can see it [here](https://github.com/aloisdg/Ascolorii/blob/master/README.md).
It could be a nice add to fetch. What do you think?

Cheers,

**Comment by dylanaraps** [comment] 2016-01-27 10:50
Sounds like a neat idea.

I've started working on implementing ascii support, here's what I've got so far:

![1](http://i.imgur.com/JXGKqvz.png)

**Comment by dylanaraps** [comment] 2016-01-27 11:23
We can also easily implement screenfetch ascii logos.

![arch](http://i.imgur.com/vvlRJqc.png)

**Comment by aloisdg** [comment] 2016-01-27 11:31
I was thinking ascii art for the color palette (like I do in ascolorii), but implement ascii art as main pitcure level is a great idea too! :)

**Comment by aloisdg** [comment] 2016-01-27 11:34
It would be nice for both of our project to be able to scale the ascii art file. A work around would to use a tool to convert ascii art to svg format since svg support vectorization.

**Comment by dylanaraps** [comment] 2016-01-27 11:36
I've just pushed the base ascii support to master, you can use it like this:

```sh
fetch --ascii "path/to/ascii.txt" --ascii_color "4"
```

Please test it out!

**Comment by dylanaraps** [comment] 2016-01-27 11:36
> I was thinking ascii art for the color palette (like I do in ascolorii), but implement ascii art as main pitcure level is a great idea too! :)

Ah, I see.

This should be easy to implement too!

**Comment by aloisdg** [comment] 2016-01-27 12:58
> Please test it out!

Sure I will!

> I'm not going to ship any ascii with fetch, I think it should be up to the user.

Sure you are right. You should not cluter the project with this,

**Comment by dylanaraps** [comment] 2016-01-27 22:21
I've run into an issue while adding support for printing ascii art similar to the terminal color blocks. We need to insert padding to each line of ascii art so that it's inline with the text but I can't seem to do it without a *really* slow `while read line` statement. 

Any ideas?

**Comment by dylanaraps** [comment] 2016-01-28 03:11
I've decided on shipping distro logos with fetch. The distro logos will work with the distro detection and will be displayed according to detected distro exactly like screenfetch. 

Here's what the file structure will probably look like:

- fetch.sh
- ascii
    - distros
        - arch.txt
        - ubuntu.txt
        - etc

**Comment by dylanaraps** [comment] 2016-01-28 08:55
Displaying the current distro's ascii art is finished in my local branch, I'm just doing some cleanup before I push it to master. Here are some scrots:

![arch](http://i.imgur.com/tgAPJv2.png)
![gentoo](http://i.imgur.com/1LbPxWP.png)

**Comment by aloisdg** [comment] 2016-01-28 08:56
Neat ! You nailed it.

**Comment by dylanaraps** [comment] 2016-01-28 09:15
I just pushed it to master, see this faq question to enable it.

https://github.com/dylanaraps/fetch#how-do-i-enable-screenfetch-mode

It needs testing very badly. :)

**Comment by dylanaraps** [comment] 2016-01-28 09:24
I'm testing Windows, BSD and a few Linux distros. It's confirmed working in:

- [X] Windows
- [X] FreeBSD
- [ ] OpenBSD
- [ ] NetBSD
- [X] Arch
- [ ] Elementary OS

**Comment by dylanaraps** [comment] 2016-01-28 13:21
@mclado, are you able to test ascii support on your OS X system?

Here's how you can test it out:

https://github.com/dylanaraps/fetch#how-do-i-enable-screenfetch-mode

This is the issue page for it, so if you've got any issues or ideas post them below. :)

**Comment by mclado** [comment] 2016-01-28 14:09
Hmm, I am getting this error.
readlink: illegal option -- f     
usage: readlink [-n] [file ...]
Just checking out why but I don't get it.

**Comment by dylanaraps** [comment] 2016-01-28 14:12
It seems out that `readline` on OS X is missing the `-f` flag(?). I'll have a look at alternatives to readlink or a workaround for OS X.

**Comment by dylanaraps** [comment] 2016-01-28 14:26
I also just realised that we need a standard location to store the distro ascii art.

**Comment by mclado** [comment] 2016-01-28 14:49
Hmm, this looks like the easiest solution instead of other things in just googled.

http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by dylanaraps** [comment] 2016-01-28 15:06
Thanks for the link, a modified version of that is in master and the ascii art should work for you now.

**Comment by dylanaraps** [comment] 2016-01-28 15:36
Awesome!

**Comment by dylanaraps** [comment] 2016-01-29 09:50
I don't think it's possible to add ascii blocks similar to your script to fetch. I ran into multiple issues when implementing it myself and I couldn't get it to a point where I was happy with it.

You *can* use your script with fetch very easily. Just add this line to the `printinfo` function at the top like so:

```sh
printinfo () {
    info title
    info underline

    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory

    /path/to/ascolorii ~/skull.txt
    # etc ...
}
```

I'm closing this issue as the distro ascii stuff is complete now and I don't have any plans to add ascii block support any time soon.

**Closed by dylanaraps** 2016-01-29 09:50 UTC
Labels: enhancement

**Comment by aloisdg** [comment] 2016-01-29 10:16
It will do the job. Thank you for your work.
